# Generated by Django 5.2.1 on 2025-05-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='It is preferable to leave this field blank so that it will be filled in automatically.', unique=True, verbose_name='slug'),
        ),
    ]
