# Generated by Django 5.2.1 on 2025-05-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'blog posts'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Categories',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='comment',
            name='display_name',
            field=models.CharField(max_length=100, verbose_name='display name'),
        ),
    ]
