# Generated by Django 5.2.1 on 2025-05-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_options_rename_categories_post_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pub', 'published'), ('SCD', 'scheduled'), ('drf', 'draft')], default='drf', max_length=3, verbose_name='status'),
        ),
    ]
