# Generated by Django 5.2.1 on 2025-05-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pub', 'published'), ('drf', 'draft'), ('rjt', 'scheduled')], default='drf', max_length=3, verbose_name='status'),
        ),
    ]
