# Generated by Django 5.2.1 on 2025-05-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_managers_post_reading_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reading_time',
            field=models.PositiveIntegerField(blank=True, help_text='In minutes', null=True, verbose_name='reading_time'),
        ),
    ]
