# Generated by Django 5.2.1 on 2025-05-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='It is preferable to leave this field blank so that it will be filled in automatically.', unique=True),
        ),
    ]
